name: antiviral-pot
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.4=pyhd8ed1ab_1
  - asttokens=3.0.1=pyhd8ed1ab_0
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - comm=0.2.3=pyhe01879c_0
  - debugpy=1.8.16=py311h50f4ffc_1
  - decorator=5.2.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.3=h50f4ffc_4
  - ipykernel=7.1.0=pyh5552912_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.7.0=pyhcf101f3_0
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - krb5=1.21.3=h237132a_0
  - libcxx=20.1.8=hd7fd590_1
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libexpat=2.7.3=h50f4ffc_4
  - libffi=3.4.4=hca03da5_1
  - libsodium=1.0.20=h99b78c6_0
  - libzlib=1.3.1=h5f15de7_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - ncurses=6.5=hee39554_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openssl=3.6.0=h5503f6c_0
  - packaging=25.0=pyh29332c3_1
  - parso=0.8.5=pyhcf101f3_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pip=25.3=pyhc872135_0
  - platformdirs=4.5.1=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.0.0=py311haa24f5a_1
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - python=3.11.14=hf701271_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - pyzmq=27.1.0=py311h5a8c52c_1
  - readline=8.3=h0b18652_0
  - setuptools=80.9.0=py311hca03da5_0
  - six=1.17.0=pyhe01879c_1
  - sqlite=3.51.0=hab6afd1_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.15=hcd8a7d5_0
  - tornado=6.5.4=py311haa24f5a_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=py311hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zeromq=4.3.5=h888dc83_9
  - zlib=1.3.1=h5f15de7_0
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - anyio==4.12.0
      - asciitree==0.3.3
      - attrs==25.4.0
      - authlib==1.6.6
      - backcall==0.2.0
      - beautifulsoup4==4.14.3
      - biotite==1.5.0
      - biotraj==1.2.2
      - bleach==6.3.0
      - boto3==1.35.99
      - botocore==1.35.99
      - certifi==2025.11.12
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - click==8.3.1
      - cloudpickle==3.1.2
      - contourpy==1.3.3
      - cryptography==46.0.3
      - cycler==0.12.1
      - datamol==0.12.5
      - defusedxml==0.7.1
      - deprecated==1.3.1
      - docopt==0.6.2
      - fasteners==0.20
      - fastjsonschema==2.21.2
      - fastpdb==1.3.3
      - fonttools==4.61.1
      - frozenlist==1.8.0
      - fsspec==2025.12.0
      - future==1.0.0
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - hyperopt==0.2.7
      - idna==3.11
      - importlib-resources==6.5.2
      - ipython==8.12.3
      - jinja2==3.1.6
      - jmespath==1.0.1
      - joblib==1.5.3
      - jsonschema==4.26.0
      - jsonschema-specifications==2025.9.1
      - jupyterlab-pygments==0.3.0
      - kiwisolver==1.4.9
      - loguru==0.7.3
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - matplotlib==3.10.8
      - mdurl==0.1.2
      - mistune==3.2.0
      - msgpack==1.1.2
      - multidict==6.7.0
      - nbclient==0.10.4
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - networkx==3.6.1
      - numcodecs==0.15.1
      - numpy==2.4.0
      - pandas==2.3.3
      - pandocfilters==1.5.1
      - pickleshare==0.7.5
      - pillow==12.0.0
      - polaris-lib==0.13.0
      - propcache==0.4.1
      - py4j==0.10.9.9
      - pyarrow==17.0.0
      - pycparser==2.23
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pydantic-settings==2.12.0
      - pyparsing==3.3.1
      - pyroaring==1.0.3
      - python-dotenv==1.2.1
      - pytz==2025.2
      - pyyaml==6.0.3
      - rdkit==2025.9.3
      - referencing==0.37.0
      - requests==2.32.5
      - rich==14.2.0
      - rpds-py==0.30.0
      - s3transfer==0.10.4
      - scikit-learn==1.8.0
      - scipy==1.16.3
      - seaborn==0.13.2
      - selfies==2.2.0
      - shellingham==1.5.4
      - soupsieve==2.8.1
      - threadpoolctl==3.6.0
      - tinycss2==1.4.0
      - tqdm==4.67.1
      - typer==0.21.0
      - typing-inspection==0.4.2
      - tzdata==2025.3
      - urllib3==2.6.2
      - webencodings==0.5.1
      - wrapt==2.0.1
      - xgboost==3.1.2
      - yarg==0.1.9
      - yarl==1.22.0
      - zarr==2.18.7
prefix: /Users/femisegvn/Coding/miniconda3/envs/antiviral-pot
